//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HtmlTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceMain {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMain() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HtmlTests.ResourceMain", typeof(ResourceMain).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;&lt;html lang=&quot;en&quot;&gt;&lt;head&gt;&lt;/head&gt;&lt;body&gt;&lt;div id=&quot;imgBank&quot;&gt;
        ///&lt;img id=&quot;btnMoreExamples-default&quot; src=&quot;images/btnMoreExamples-default.png&quot;&gt;
        ///&lt;img id=&quot;btnMoreExamples-hover&quot; src=&quot;images/btnMoreExamples-hover.png&quot;&gt;
        ///&lt;img id=&quot;btnMoreExamples-press&quot; src=&quot;images/btnMoreExamples-press.png&quot;&gt;
        ///&lt;img id=&quot;btnPlayAgain-default&quot; src=&quot;images/btnPlayAgain-default.png&quot;&gt;
        ///&lt;img id=&quot;btnPlayAgain-hover&quot; src=&quot;images/btnPlayAgain-hover.png&quot;&gt;
        ///&lt;img id=&quot;btnPlayAgain-press&quot; src=&quot;images/btnPlayAgain-press.png&quot;&gt;
        ///&lt;img id=&quot;btnSh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImageMapHTML {
            get {
                return ResourceManager.GetString("ImageMapHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax: HtmlTests.exe.
        /// </summary>
        internal static string Syntax {
            get {
                return ResourceManager.GetString("Syntax", resourceCulture);
            }
        }
    }
}
