//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Html {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceMain {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMain() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Html.ResourceMain", typeof(ResourceMain).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:(?s:(\&lt;!--.*?--\&gt;)|(\&lt;\!{0,1}(?&lt;tag&gt;[-_./a-z0-9]+)(\s+[-_.a-z0-9]+\s*(=\s*(&quot;[^&quot;]*?&quot;|&apos;[^&apos;]*?&apos;|[-_.a-z0-9%@#&amp;?=]+)){0,1})*?\s*/{0,1}\&gt;))).
        /// </summary>
        internal static string originalrxHtmlTags {
            get {
                return ResourceManager.GetString("originalrxHtmlTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;!(\&lt;|/|\!))\b(?&lt;name&gt;[a-z]+[a-z0-9-_\.\:]*)\s*(=\s*(&apos;(?&lt;value&gt;[^&apos;]*?)&apos;|&quot;(?&lt;value&gt;[^&quot;]*?)&quot;|(?&lt;value&gt;([a-zA-Z0-9#-_\(\)]+?(%|\w*?)))(\s+|&gt;))){0,1}.
        /// </summary>
        internal static string rxHtmlAttributes {
            get {
                return ResourceManager.GetString("rxHtmlAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?s:\&lt;!--\s*(?&lt;content&gt;.+?)\s*--\&gt;).
        /// </summary>
        internal static string rxHtmlCommentText {
            get {
                return ResourceManager.GetString("rxHtmlCommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&lt;/|&lt;)(?&lt;result&gt;(\?|\!--|\!([A-Za-z]+([A-Za-z0-9-_\.])*){0,1}(:([A-Za-z]+([A-Za-z0-9-_\.])*){0,1}){0,1}|([A-Za-z]+([A-Za-z0-9-_\.])*){0,1}(:([A-Za-z]+([A-Za-z0-9-_\.])*){0,1}){0,1})).
        /// </summary>
        internal static string rxHtmlElementType {
            get {
                return ResourceManager.GetString("rxHtmlElementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:(?s:\s*(\&lt;!--.*?--\&gt;)|(\&lt;\!{0,1}(?&lt;tag&gt;[^ \t\&gt;]+)\s*([^\&gt;]*?)\&gt;)\s*)).
        /// </summary>
        internal static string rxHtmlTags {
            get {
                return ResourceManager.GetString("rxHtmlTags", resourceCulture);
            }
        }
    }
}
